# coding: utf-8

"""
    Solar0 REST Interface for adapters

    REST Interface for communication with adapters

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from solar0_python_sdk.api.solar_api import SolarApi


class TestSolarApi(unittest.TestCase):
    """SolarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolarApi()

    def tearDown(self) -> None:
        pass

    def test_solar_day_post(self) -> None:
        """Test case for solar_day_post

        Add day data to influxdb
        """
        pass

    def test_solar_min_post(self) -> None:
        """Test case for solar_min_post

        Add minute data to influxdb
        """
        pass


if __name__ == '__main__':
    unittest.main()
