# coding: utf-8

"""
    Solar0 REST Interface for adapters

    REST Interface for communication with adapters

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from solar0_python_sdk.models.data_last_datapoint_time import DataLastDatapointTime

class TestDataLastDatapointTime(unittest.TestCase):
    """DataLastDatapointTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataLastDatapointTime:
        """Test DataLastDatapointTime
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataLastDatapointTime`
        """
        model = DataLastDatapointTime()
        if include_optional:
            return DataLastDatapointTime(
                time = ''
            )
        else:
            return DataLastDatapointTime(
        )
        """

    def testDataLastDatapointTime(self):
        """Test DataLastDatapointTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
