# coding: utf-8

# flake8: noqa
"""
    Solar0 REST Interface for adapters

    REST Interface for communication with adapters

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from solar0_python_sdk.models.data_solar_day_datapoint import DataSolarDayDatapoint
from solar0_python_sdk.models.data_solar_inverter import DataSolarInverter
from solar0_python_sdk.models.data_solar_min_datapoint import DataSolarMinDatapoint
