# coding: utf-8

# flake8: noqa

"""
    Solar0 REST Interface for adapters

    REST Interface for communication with adapters

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from solar0_python_sdk.api.solar_api import SolarApi

# import ApiClient
from solar0_python_sdk.api_response import ApiResponse
from solar0_python_sdk.api_client import ApiClient
from solar0_python_sdk.configuration import Configuration
from solar0_python_sdk.exceptions import OpenApiException
from solar0_python_sdk.exceptions import ApiTypeError
from solar0_python_sdk.exceptions import ApiValueError
from solar0_python_sdk.exceptions import ApiKeyError
from solar0_python_sdk.exceptions import ApiAttributeError
from solar0_python_sdk.exceptions import ApiException

# import models into sdk package
from solar0_python_sdk.models.data_last_datapoint_time import DataLastDatapointTime
from solar0_python_sdk.models.data_solar_day_datapoint import DataSolarDayDatapoint
from solar0_python_sdk.models.data_solar_inverter import DataSolarInverter
from solar0_python_sdk.models.data_solar_min_datapoint import DataSolarMinDatapoint
